(function() {var implementors = {};
implementors['lzw'] = ["impl&lt;W: <a class='trait' href='lzw/trait.BitWriter.html' title='lzw::BitWriter'>BitWriter</a>&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='lzw/struct.Encoder.html' title='lzw::Encoder'>Encoder</a>&lt;W&gt;",];implementors['gif'] = ["impl&lt;W: <a class='trait' href='http://doc.rust-lang.org/nightly/std/io/trait.Write.html' title='std::io::Write'>Write</a>&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='gif/struct.Writer.html' title='gif::Writer'>Writer</a>&lt;W&gt;",];implementors['flate2'] = ["impl&lt;W: <a class='trait' href='http://doc.rust-lang.org/nightly/std/io/trait.Write.html' title='std::io::Write'>Write</a>&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='flate2/write/struct.GzEncoder.html' title='flate2::write::GzEncoder'>EncoderWriter</a>&lt;W&gt;",];implementors['png'] = ["impl&lt;W: <a class='trait' href='http://doc.rust-lang.org/nightly/std/io/trait.Write.html' title='std::io::Write'>Write</a>&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='png/struct.Writer.html' title='png::Writer'>Writer</a>&lt;W&gt;",];implementors['image'] = ["impl&lt;'a, W&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='gif/encoder/struct.BlockWriter.html' title='gif::encoder::BlockWriter'>BlockWriter</a>&lt;'a, W&gt;","impl&lt;W&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='gif/encoder/struct.Writer.html' title='gif::encoder::Writer'>Writer</a>&lt;W&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
